#!/bin/bash
function create_svn_repos() 
{
	home_dir="/home/ghh"
	svn_dir=$home_dir/svn-repos/$1
	svn_co_dir=$home_dir/$1
	trac_env=/var/www/trac
	svnadmin create $svn_dir
	cd $svn_dir/hooks
	echo '/usr/bin/trac-admin /var/www/trac changeset added "$1" "$2"'>post-commit
	chmod ug+x post-commit
	echo '/usr/bin/trac-admin /var/www/trac changeset modified "$1" "$2"'>pre-revprop-change
	chmod ug+x pre-revprop-change
	cd $home_dir
	svn co file://$svn_dir $1
}
create_svn_repos $*


