#!/bin/bash
function create_svn_repos() 
{
	home_dir="/home/ghh"
	svn_dir=$home_dir/svn-repos/$1
	svn_co_dir=$home_dir/$1
	trac_env=/var/www/trac
	svnadmin create $svn_dir
	cd $home_dir
	svn co file://$svn_dir $1
}
create_svn_repos $*


