#!/bin/bash
#(by fevernova.life@gmail.com)
#2007年 10月 25日 星期四 22:52:17 CST


function fib { 
    if [ "$1" = "0" ];then 
       echo 0
    else if [ "$1" = "1" ];then
            echo 1 
         else 
             echo $((`fib $(( $1 - 1 ))`+`fib $(( $1 - 2 ))`))
         fi
    fi
}

fib 1
fib 2
fib 3
fib 4
fib 5
fib 6
fib 7
fib 8
fib 9
fib 10

