#!/bin/sh
svn_repos_dir=/home/ghh/svn-repos
svn_project_hooks_dir=$svn_repos_dir/$1/hooks
rm -rf post-commit pre-revprop-change
echo '#!/bin/sh'>post-commit
echo '#!/bin/sh'>pre-revprop-change
echo 'trac-admin /var/www/trac changeset added "$1" "$2"'>>post-commit
echo 'trac-admin /var/www/trac changeset modified "$1" "$2"'>>pre-revprop-change

sudo chown www-data:www-data post-commit pre-revprop-change
sudo chmod a+x post-commit pre-revprop-change
sudo rm $svn_project_hooks_dir/post-commit $svn_project_hooks_dir/pre-revprop-change
mv post-commit $svn_project_hooks_dir
mv pre-revprop-change $svn_project_hooks_dir

