#!/bin/bash
# date : 2011.11.01
# goal : this system will move to other machine
# usage: just run it.
HOME_DIR=/home/ghh
DUMP_DIR=/home/ghh/dump

SVN_REPOS=/home/ghh/svn-repos 
SVN_DUMP_FILE=$DUMP_DIR/svn-dump

TRAC_ENV=/var/www/trac
TRAC_DUMP_ENV=$DUMP_DIR/trac-dump

PSQL_DUMP_DIR=$DUMP_DIR/psql_dump
DB_LIST=("db_test" "db_asac" "db_blog")

CONFIG_FILES_DIR=$DUMP_DIR/config-files

FILES_AND_DIRS_DUMP=$DUMP_DIR/files_dirs
FILE_DIRECTORY_LIST=("/var/www" "$HOME_DIR/workspace" "$HOME_DIR/useful-tip" "$HOME_DIR/software" "$HOME_DIR/temp" "$HOME_DIR/pictures" "$HOME_DIR/download" "$HOME_DIR/documents" "$HOME_DIR/music")
# for svn
function svn_dump(){
	for file in `ls $SVN_REPOS`
	do 
		if [ -d $file ];then
			echo entring directory: $file
			echo dump to the file : $SVN_DUMP_FILE/$file.`date +%F`.dump
			svnadmin dump $file > $SVN_DUMP_FILE/$file.`date +%F`.dump
		fi
	done
}
# for trac
function trac_dump(){
	echo "trac-admin $TRAC_ENV hotcopy $TRAC_DUMP_ENV"
	trac-admin $TRAC_ENV hotcopy $TRAC_DUMP_ENV

}
# for postgresql
# see more : http://www.pgsqldb.org/pgsqldoc-cvs/backup.html
function sql_dump(){
	echo "dump all sql to $PSQL_DUMP_DIR. use psql -f 'infile' postgres to recovery."
	for dbname in ${DB_LIST[*]}
	do 
	pg_dump $dbname > $PSQL_DUMP_DIR/$dbname.`date +%F`.dump
	done
}
# for the configure files.
function config_dump(){
	cp /etc/apt/sources.list $CONFIG_FILES_DIR/sources.list
	cp ~/.bash_aliases $CONFIG_FILES_DIR/bash_aliases
	cp ~/.vimrc $CONFIG_FILES_DIR/vimrc
}

# files & directories need to copy
function files_dirs_dump(){
	for dir in ${FILE_DIRECTORY_LIST[*]}
	do
		echo $dir
	#	ls $dir/*
		echo ${dir##*/}
		tar -cvf $FILES_AND_DIRS_DUMP/${dir##*/}.tar.gz $dir
	done

}

##############################
#### we dump form here ######
#############################
rm -rf $DUMP_DIR
mkdir $DUMP_DIR
mkdir $SVN_DUMP_FILE
mkdir $PSQL_DUMP_DIR
mkdir $CONFIG_FILES_DIR
mkdir $FILES_AND_DIRS_DUMP

#ok now . 
svn_dump
trac_dump
sql_dump
config_dump
files_dirs_dump
cd $HOME_DIR
tar -cvf system.dump.`date +%F`.tar.gz $DUMP_DIR


##############################
#######dump done !############
##############################
